#!/usr/bin/env bash

umask 0002

export PATH="/home/b0qi/anaconda3/bin:/home/b0qi/anaconda3/condabin:${PATH}"

export ASHARE_RAWDATA_PRELOAD_RAY_SESSION_NAME="ashare_rawdata_preload_ray_gkh_ray"
export ASHARE_RAWDATA_PRELOAD_RAY_HOST="127.0.0.1"
export ASHARE_RAWDATA_PRELOAD_RAY_PORT="43680"
export ASHARE_RAWDATA_PRELOAD_RAY_OBJECT_STORE_BYTES="200000000000"

export ASHARE_RAWDATA_PRELOAD_RAY_BASE_DIR="/home/gkh_ray/.config/ashare_rawdata/preload_ray"
export ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_DIR="/home/gkh_ray/rp"
export ASHARE_RAWDATA_PRELOAD_RAY_ADDRESS_FILE="/home/gkh_ray/.config/ashare_rawdata/preload_ray/address"
export ASHARE_RAWDATA_PRELOAD_RAY_METADATA_PATH="/home/gkh_ray/.config/ashare_rawdata/preload_ray/cluster.json"
export ASHARE_RAWDATA_PRELOAD_RAY_LOG_PATH="/home/gkh_ray/.local/state/ashare_rawdata/ray_preload_isolated.log"
export ASHARE_RAWDATA_PRELOAD_STATE_PATH="/home/gkh_ray/.local/state/ashare_rawdata/ashare_rawdata_preload_state.json"
export ASHARE_RAWDATA_PRELOAD_SHARED_GROUP="anaconda_group"
export ASHARE_RAWDATA_PRELOAD_SHARED_USER="gkh"

export ASHARE_RAWDATA_PRELOAD_RAY_MIN_WORKER_PORT="43700"
export ASHARE_RAWDATA_PRELOAD_RAY_MAX_WORKER_PORT="44699"
export ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_LISTEN_PORT="43690"
export ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_GRPC_PORT="43691"
export ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_ENV_AGENT_PORT="43692"
export ASHARE_RAWDATA_PRELOAD_RAY_METRICS_EXPORT_PORT="43693"
export ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_PORT="43694"
export ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_GRPC_PORT="43695"
export ASHARE_RAWDATA_PRELOAD_RAY_AUTOSCALER_METRIC_PORT="43696"
export ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_METRIC_PORT="43697"
