#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/gkh/claude_tasks/ashare_rawdata"
cd "$ROOT"

source orchestration/preload_ray_gkh_ray.env.sh

sudo -u gkh_ray -H env \
  ASHARE_RAWDATA_PRELOAD_RAY_SESSION_NAME="$ASHARE_RAWDATA_PRELOAD_RAY_SESSION_NAME" \
  ASHARE_RAWDATA_PRELOAD_RAY_HOST="$ASHARE_RAWDATA_PRELOAD_RAY_HOST" \
  ASHARE_RAWDATA_PRELOAD_RAY_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_OBJECT_STORE_BYTES="$ASHARE_RAWDATA_PRELOAD_RAY_OBJECT_STORE_BYTES" \
  ASHARE_RAWDATA_PRELOAD_RAY_BASE_DIR="$ASHARE_RAWDATA_PRELOAD_RAY_BASE_DIR" \
  ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_DIR="$ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_DIR" \
  ASHARE_RAWDATA_PRELOAD_RAY_ADDRESS_FILE="$ASHARE_RAWDATA_PRELOAD_RAY_ADDRESS_FILE" \
  ASHARE_RAWDATA_PRELOAD_RAY_METADATA_PATH="$ASHARE_RAWDATA_PRELOAD_RAY_METADATA_PATH" \
  ASHARE_RAWDATA_PRELOAD_RAY_LOG_PATH="$ASHARE_RAWDATA_PRELOAD_RAY_LOG_PATH" \
  ASHARE_RAWDATA_PRELOAD_STATE_PATH="$ASHARE_RAWDATA_PRELOAD_STATE_PATH" \
  ASHARE_RAWDATA_PRELOAD_RAY_MIN_WORKER_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_MIN_WORKER_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_MAX_WORKER_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_MAX_WORKER_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_LISTEN_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_LISTEN_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_GRPC_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_AGENT_GRPC_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_ENV_AGENT_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_ENV_AGENT_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_METRICS_EXPORT_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_METRICS_EXPORT_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_GRPC_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_GRPC_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_AUTOSCALER_METRIC_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_AUTOSCALER_METRIC_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_METRIC_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_DASHBOARD_METRIC_PORT" \
  bash orchestration/start_rawdata_preload_ray.sh
