#!/usr/bin/env bash
set -euo pipefail

ROOT="/home/gkh/claude_tasks/ashare_rawdata"
cd "$ROOT"

source orchestration/preload_ray_gkh_ray.env.sh

sudo -u gkh_ray -H env \
  ASHARE_RAWDATA_PRELOAD_RAY_SESSION_NAME="$ASHARE_RAWDATA_PRELOAD_RAY_SESSION_NAME" \
  ASHARE_RAWDATA_PRELOAD_RAY_HOST="$ASHARE_RAWDATA_PRELOAD_RAY_HOST" \
  ASHARE_RAWDATA_PRELOAD_RAY_PORT="$ASHARE_RAWDATA_PRELOAD_RAY_PORT" \
  ASHARE_RAWDATA_PRELOAD_RAY_BASE_DIR="$ASHARE_RAWDATA_PRELOAD_RAY_BASE_DIR" \
  ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_DIR="$ASHARE_RAWDATA_PRELOAD_RAY_RUNTIME_DIR" \
  ASHARE_RAWDATA_PRELOAD_RAY_ADDRESS_FILE="$ASHARE_RAWDATA_PRELOAD_RAY_ADDRESS_FILE" \
  ASHARE_RAWDATA_PRELOAD_RAY_METADATA_PATH="$ASHARE_RAWDATA_PRELOAD_RAY_METADATA_PATH" \
  ASHARE_RAWDATA_PRELOAD_RAY_LOG_PATH="$ASHARE_RAWDATA_PRELOAD_RAY_LOG_PATH" \
  bash orchestration/stop_rawdata_preload_ray.sh
